### ISSUE TITLE
resolveJsonModule doesn't work

### ISSUE THREAD

**Issue by pauldraper** [bazelbuild/rules_nodejs#1109]
# 🐞 bug report

### Affected Rule

ts_library

### Is this a regression?

No.

### Description

`resolveJsonModule` is not supported.

ts_library supports only .ts and .tsx sources.

https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by thesayyn** [comment]
Matter of fact it does but it requires some configuration in tsconfig.json file. 

Like so 

```
{
  ...
  "bazelOptions": {
    "devmodeTargetOverride": "es2018",
    "googmodule": true
  }
}
```
Keep in mind this is just a workaround. worked well in my case.

**Comment by alexeagle** [comment]
I'm surprised that workaround works because I thought ts_library restricts inputs
https://github.com/bazelbuild/rules_nodejs/blob/master/packages/typescript/src/internal/build_defs.bzl#L279

**Comment by pauldraper** [comment]
Yeah, it doesn't work (because of the reason both @alexeagle and I mentioned).

**Comment by Toxicable** [comment]
I think it hsould be reasonable to allow `.json` imports of `tsc` allows it

**Comment by marcus-sa** [comment]
Shouldn't `.js` be allowed as well?

**Comment by jwnewman12** [comment]
Wouldn't this be blocked anyway due to the use of the UMD module type? Typescript doesn't allow resolveJsonModule with UMD. https://github.com/microsoft/TypeScript/pull/26825/files#diff-942ae3cd2a8bbd85ed86a60cd7c43307R7015  (I can't imagine why .. we are talking about static json files here, it shouldn't be this hard :)).

`error TS5071: Option '--resolveJsonModule' can only be specified when module code generation is 'commonjs', 'amd', 'es2015' or 'esNext'.`

Our tsconfig.json has `"module": "commonjs"`. I didn't understand the error the other day (we are new and trying to pilot bazel). I hastily removed resolveJsonModule and forgot about it. 

Then, I set about patching this in to your rules (I couldn't add .json into src), and eventually, I think I got that right, the symlinks are finally there and valid, but still the json files weren't resolved.  (I could publish this patch if interested, I believe it's close though I didn't update tests).

Now I see I forgot about the setting in the tsconfig. I put that back .. and despite my efforts to patch I am still blocked, due to the above with UMD. I suppose I will try creating a json.d.ts file as described here https://stackoverflow.com/a/40473566 and try to move on.

**Comment by longlho** [comment]
I believe this is fixed

**Comment by alexeagle** [comment]
yeah your https://github.com/bazelbuild/rules_nodejs/pull/1995 I think, thanks

**Comment by vpanta** [comment]
This is not fixed, as I'm running into it now on [2.0.1](https://github.com/bazelbuild/rules_nodejs/releases/tag/2.0.1) (which should be after #1995, which only fixed this for `ts_project` I believe)

Is fixing this for `ts_library` a lost cause?

**Comment by alexeagle** [comment]
Yeah sorry still true for ts_library.
Can be fixed locally on the 3.x branch which no longer syncs with google3

**Comment by vpanta** [comment]
I took a shot at it for ts_library, without necessarily needing to touch the code coming out of `rules_typescript`

Let me know what y'all think, we'll probably use a local branch of this for the time-being.

**Comment by tomasdev** [comment]
If I'm on 3.0.0-rc.1 what's the right way to use `import data from 'data.json'` ?

I think I'm able to do it via Rollup, but would like to have the concatjs_devserver also working.

**Comment by alexeagle** [comment]
@tomasdev which rule are you using that doesn't understand the json import?

**Comment by tomasdev** [comment]
@alexeagle hey! thanks, I'm tracking it under #2365 -- it has an isolated test scenario as well
