### ISSUE TITLE
Bazel CI: rules_nodejs failing on Windows

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/rules_nodejs#3328]
rules_nodejs is failing with Bazel 5.0.0 on Windows:
https://buildkite.com/bazel/rules-nodejs-nodejs/builds/11725#1f45dc18-12ba-41cf-8a47-f8e8aa3656e4
```
(00:17:39) ERROR: C:/b/bk-windows-p9mw/bazel/rules-nodejs-nodejs/internal/node/test/chdir/BUILD.bazel:20:16: output 'internal/node/test/chdir/package.json' was not created
(00:17:39) ERROR: C:/b/bk-windows-p9mw/bazel/rules-nodejs-nodejs/internal/node/test/chdir/BUILD.bazel:20:16: Action internal/node/test/chdir/package.json failed: not all outputs were created or valid
```

It's also failing with Bazel@HEAD at a previously green commit: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2366#7f3630d6-219e-4373-86ff-06a5c36451c1

Looks like some infra rules_nodejs depends on has changed? Please help looking into it!

**Comment by meteorcloudy** [comment]
FYI @gregmagolan

**Comment by alexeagle** [comment]
I tried and failed to understand how it's possible that it went red in that way, without a code change in rules_nodejs or Bazel.

I guess we'll just have to stop running that on Windows...

**Comment by meteorcloudy** [comment]
Can you reproduce the failure locally? Do you think it could somehow be caused by remote cache poison?

**Comment by meteorcloudy** [comment]
But feel free to temporarily disable that test on Windows.

**Comment by alexeagle** [comment]
"temporarily" will be a total lie here, I really don't imagine us ever coming back to the TODO, but still it's better than leaving this red I guess.
Our tests against bazel 4.2.2 are also red on CircleCI which is probably an unrelated breakage? 
`Error in download_and_extract: java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.50.19-ca-jdk11.0.12/zulu11.50.19-ca-jdk11.0.12-linux_x64.tar.gz] to /home/circleci/.cache/bazel/_bazel_circleci/02fc451c9ce3986cffaddce25971cb5b/external/remotejdk11_linux/temp17128203695807064637/zulu11.50.19-ca-jdk11.0.12-linux_x64.tar.gz: Bytes read 17563520 but wanted 202599005`

**Comment by alexeagle** [comment]
that one just went red on our stable branch
https://app.circleci.com/pipelines/github/bazelbuild/rules_nodejs?branch=stable&filter=all
@meteorcloudy I think this is a fetch that Bazel makes? I don't have "zulu" anywhere in rules_nodejs

**Comment by meteorcloudy** [comment]
Yes, that's the remote JDK Bazel needs to download, seems like a flake?

> "temporarily" will be a total lie here, I really don't imagine us ever coming back to the TODO

It depends how important you think your Windows support should be.

**Comment by alexeagle** [comment]
this is fixed, in the sense that our buildkite is green at HEAD again.

I'd like to keep Windows working of course. rules_nodejs does have windows users, even if none of my current clients depend on that.

**Comment by meteorcloudy** [comment]
> this is fixed, in the sense that our buildkite is green at HEAD again.

What do you mean by "it's green at HEAD again"? It's still failing on buildkite with Bazel 5.0:
https://buildkite.com/bazel/rules-nodejs-nodejs/builds?branch=stable

**Comment by mattem** [comment]
We should be back green at head after #3347

**Comment by meteorcloudy** [comment]
Thanks, rerunning at https://buildkite.com/bazel/rules-nodejs-nodejs/builds/11772
